name: MarkCarey
favicon: null
layout_spectrum: 0.5552130723372102
typography_spectrum: 0.31691597937606275
title: Mark Carey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#364d6c'
    - '#f2fafc'
    - '#97a4b5'
    - '#1e1e1e'
    - '#777060'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6820702152326703
purpose: []
