name: MarkCarey
favicon: null
layout_spectrum: 0.5552130723372102
typography_spectrum: 0.31691597937606275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.04740567738190293
  lightness: 0.11525868927128613
  saturation: 0.9697733297944069
  rhythmicContrast: 0.6820702152326703
purpose: []
